//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BashkircevGlazkiSave
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public int AgentTypeID { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Logo { get; set; }
        public string Address { get; set; }
        public int Priority { get; set; }
        public string DirectorName { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public int TotalSales
        {
            get
            {
                return ProductSale.Sum(ps => (int?)ps.ProductCount) ?? 0;
            }
        }

        public decimal TotalSalesAmount
        {
            get
            {
                return ProductSale
                    .Sum(ps => (decimal?)(ps.ProductCount * ps.Product.MinCostForAgent)) ?? 0;
            }
        }

        public int DiscountPercent
        {
            get
            {
                var sum = TotalSalesAmount;

                if (sum < 10000)
                    return 0;

                if (sum < 50000)
                    return 5;

                if (sum < 150000)
                    return 10;

                if (sum < 500000)
                    return 20;

                return 25;
            }
        }

        public string AgentPhotoPathFull
        {
            get
            {
                if (string.IsNullOrWhiteSpace(Logo))
                    return null;

                return "." + Logo;
            }
        }


        public virtual AgentType AgentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
